### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by aAlternant** [Emberium/SimpleQIWI#2]
Привет!Первый раз качаю с github.Установил git.Через него клонировал,после запустил gitbush и написал pip install SimpleQIWI,после выдало что не существует комманды pip.Помоги!

**Comment by edilbek808** [comment]
скорее всего создатель закрыл проект, чтобы не было проблем после видео бафера

**Comment by Fastr3flex** [comment]
писать команди нада в cmd

**Comment by edilbek808** [comment]
у тебя работает?

**Comment by aAlternant** [comment]
Уже разобралсч

**Comment by MytniyPchel** [comment]
Как разобрался?

**Comment by aAlternant** [comment]
Надо было при установке py нажать PATH и после в cmd ввести

**Comment by MytniyPchel** [comment]
Что ввести?
