### ISSUE TITLE
)))

### ISSUE THREAD

**Issue by OleksaKond** [Emberium/SimpleQIWI#6]
Можна сделать перевод только с токином и номером получателя (без номера владельца токена ) ?

**Comment by EminovTagir** [comment]
Прив чел. я точно не знаю, но ты можешь мне помочь по скайпу?

**Comment by OleksaKond** [comment]
Сори но я с Украини и плохо розговариваю по русски

**Comment by EminovTagir** [comment]
можешь просто объяснить, просто у меня когда я открываю сетап у меня сразу вылетает

**Comment by OleksaKond** [comment]
давай скайп

**Comment by EminovTagir** [comment]
спасибо 
скоро скину

**Comment by EminovTagir** [comment]
YT Malkorin

**Comment by EminovTagir** [comment]
посмотри скайп

**Comment by Skleffs** [comment]
Как запускать программу?

**Comment by Salaratron** [comment]
Сам не знаю. Помогите

**Comment by CookiesPlay** [comment]
Ребят помогите я в первый раз вообще на сайте как открыть программу или запустить этот помогите плиз

**Comment by BYBondMan** [comment]
можно помощь?

**Comment by EminovTagir** [comment]
Мой скайп вверху

**Comment by BYBondMan** [comment]
я отправил запрос
